# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
reviews:
  profile: chill
  high_level_summary: true
  path_instructions:
    - path: "apps/demo/**"
      instructions: "apps/demo directory contains demo application to testing purposes, can be used for sdk usages examples"
    - path: "docs/**"
      instructions: "Contains documentation for sdk, using mdx format and hosted by mintlify"
  path_filters:
    - "!**/dist/**"
    - "!**/build/**"
    - "!**/coverage/**"
    - "!**/.next/**"
    - "!**/.nuxt/**"
    - "!**/.svelte-kit/**"
    - "!**/.turbo/**"
    - "!**/.swc/**"
    - "!**/.parcel-cache/**"
    - "!**/node_modules/**"
    - "!**/.yarn/**"
    - "!**/.pnpm-store/**"
    - "!**/*.min.{js,css}"
    - "!**/*.map"
    - "!**/public/**"
    - "!**/*.svg"
    - "!**/*lock*.{json,yaml,yml}"