/**
 * Unit tests for skills install CLAUDE.md generation
 */

import { buildSkillsSection, ensureClaudeMdSkillsInstructions } from '../install';

// Mock dependencies
jest.mock('../../../core/version', () => ({
  getSelfVersion: () => '1.0.0-test',
}));

jest.mock('../catalog', () => ({
  loadCatalog: () => ({
    version: 1,
    skills: [
      { name: 'skill-alpha', description: 'Use when you want to build alpha components', tags: [], category: 'dev' },
      { name: 'skill-beta', description: 'Testing helpers and utilities', tags: [], category: 'test' },
    ],
  }),
  getCatalogDir: () => '/mock/catalog',
}));

let mockFiles: Record<string, string> = {};

jest.mock('@frontmcp/utils', () => ({
  fileExists: jest.fn(async (p: string) => p in mockFiles),
  readFile: jest.fn(async (p: string) => mockFiles[p] ?? ''),
  writeFile: jest.fn(async (p: string, content: string) => {
    mockFiles[p] = content;
  }),
  ensureDir: jest.fn(),
  cp: jest.fn(),
}));

beforeEach(() => {
  mockFiles = {};
  jest.clearAllMocks();
});

describe('buildSkillsSection', () => {
  const skills = [
    { name: 'frontmcp-development', description: 'Use when you want to create tools, resources, and prompts' },
    { name: 'frontmcp-testing', description: 'Testing utilities and e2e helpers' },
  ];

  it('should generate section with version markers', () => {
    const section = buildSkillsSection('1.2.3', skills);

    expect(section).toContain('<!-- frontmcp:skills-start v1.2.3 -->');
    expect(section).toContain('<!-- frontmcp:skills-end -->');
  });

  it('should include auto-generated attribution with version', () => {
    const section = buildSkillsSection('1.2.3', skills);

    expect(section).toContain('Auto-generated by `frontmcp skills install` (v1.2.3)');
    expect(section).toContain('do not edit manually');
  });

  it('should list all skills from input', () => {
    const section = buildSkillsSection('1.0.0', skills);

    expect(section).toContain('**frontmcp-development**');
    expect(section).toContain('**frontmcp-testing**');
  });

  it('should strip "Use when you want to" prefix from descriptions', () => {
    const section = buildSkillsSection('1.0.0', skills);

    expect(section).toContain('create tools, resources, and prompts');
    expect(section).not.toContain('Use when you want to create');
  });

  it('should include the Skills and Tools heading', () => {
    const section = buildSkillsSection('1.0.0', skills);

    expect(section).toContain('# Skills and Tools');
  });

  it('should handle empty skills list', () => {
    const section = buildSkillsSection('1.0.0', []);

    expect(section).toContain('<!-- frontmcp:skills-start');
    expect(section).toContain('<!-- frontmcp:skills-end -->');
    expect(section).not.toContain('- **');
  });
});

describe('ensureClaudeMdSkillsInstructions', () => {
  it('should create new CLAUDE.md with skills section when file does not exist', async () => {
    await ensureClaudeMdSkillsInstructions('/test/project');

    const content = mockFiles['/test/project/CLAUDE.md'];
    expect(content).toBeDefined();
    expect(content).toContain('<!-- frontmcp:skills-start v1.0.0-test -->');
    expect(content).toContain('<!-- frontmcp:skills-end -->');
    expect(content).toContain('**skill-alpha**');
    expect(content).toContain('**skill-beta**');
  });

  it('should replace existing marker-bounded block on re-run', async () => {
    mockFiles['/test/project/CLAUDE.md'] = [
      '# My Project',
      '',
      '<!-- frontmcp:skills-start v0.9.0 -->',
      '# Skills and Tools',
      'Old content here',
      '<!-- frontmcp:skills-end -->',
      '',
      '## Other Section',
      'User content preserved.',
    ].join('\n');

    await ensureClaudeMdSkillsInstructions('/test/project');

    const content = mockFiles['/test/project/CLAUDE.md'];
    expect(content).toContain('<!-- frontmcp:skills-start v1.0.0-test -->');
    expect(content).not.toContain('v0.9.0');
    expect(content).not.toContain('Old content here');
    expect(content).toContain('**skill-alpha**');
    expect(content).toContain('## Other Section');
    expect(content).toContain('User content preserved.');
  });

  it('should migrate legacy "# Skills and Tools" header to marker format', async () => {
    mockFiles['/test/project/CLAUDE.md'] = [
      '# Skills and Tools',
      'Some old hardcoded content.',
      '',
      '# Other Heading',
      'User content here.',
    ].join('\n');

    await ensureClaudeMdSkillsInstructions('/test/project');

    const content = mockFiles['/test/project/CLAUDE.md'];
    expect(content).toContain('<!-- frontmcp:skills-start v1.0.0-test -->');
    expect(content).toContain('<!-- frontmcp:skills-end -->');
    expect(content).not.toContain('Some old hardcoded content');
    expect(content).toContain('# Other Heading');
    expect(content).toContain('User content here.');
  });

  it('should migrate legacy "# Skills and Tools" when next heading is ## level', async () => {
    mockFiles['/test/project/CLAUDE.md'] = [
      '# Skills and Tools',
      'Some old hardcoded content.',
      '',
      '## Other Heading',
      'User content here.',
    ].join('\n');

    await ensureClaudeMdSkillsInstructions('/test/project');

    const content = mockFiles['/test/project/CLAUDE.md'];
    expect(content).toContain('<!-- frontmcp:skills-start v1.0.0-test -->');
    expect(content).toContain('<!-- frontmcp:skills-end -->');
    expect(content).not.toContain('Some old hardcoded content');
    expect(content).toContain('## Other Heading');
    expect(content).toContain('User content here.');
  });

  it('should prepend block when CLAUDE.md exists without any skills section', async () => {
    mockFiles['/test/project/CLAUDE.md'] = ['# My Project', '', '## Commands', 'Run yarn dev.'].join('\n');

    await ensureClaudeMdSkillsInstructions('/test/project');

    const content = mockFiles['/test/project/CLAUDE.md'];
    // Skills block should be at the top
    expect(content.indexOf('<!-- frontmcp:skills-start')).toBeLessThan(content.indexOf('# My Project'));
    // Original content preserved
    expect(content).toContain('## Commands');
    expect(content).toContain('Run yarn dev.');
  });

  it('should not produce duplicate marker blocks', async () => {
    // Run twice
    await ensureClaudeMdSkillsInstructions('/test/project');
    await ensureClaudeMdSkillsInstructions('/test/project');

    const content = mockFiles['/test/project/CLAUDE.md'];
    const startCount = (content.match(/<!-- frontmcp:skills-start/g) ?? []).length;
    const endCount = (content.match(/<!-- frontmcp:skills-end -->/g) ?? []).length;
    expect(startCount).toBe(1);
    expect(endCount).toBe(1);
  });

  it('should use skills from the manifest, not hardcoded', async () => {
    await ensureClaudeMdSkillsInstructions('/test/project');

    const content = mockFiles['/test/project/CLAUDE.md'];
    // These come from the mocked manifest
    expect(content).toContain('**skill-alpha**');
    expect(content).toContain('**skill-beta**');
    // Old hardcoded entries should NOT be present
    expect(content).not.toContain('frontmcp-development');
  });
});
