import * as path from 'path';
import { c } from '../../core/colors';
import { getSelfVersion } from '../../core/version';
import { ensureDir, fileExists, cp, readFile, writeFile } from '@frontmcp/utils';
import { loadCatalog, getCatalogDir } from './catalog';

const PROVIDER_DIRS: Record<string, string> = {
  claude: '.claude/skills',
  codex: '.codex/skills',
};

/** Start marker for the auto-generated skills block (version is appended). */
const SKILLS_BLOCK_START = '<!-- frontmcp:skills-start';
/** End marker for the auto-generated skills block. */
const SKILLS_BLOCK_END = '<!-- frontmcp:skills-end -->';
/** Legacy marker from older versions (used for migration). */
const LEGACY_SKILLS_MARKER = '# Skills and Tools';

/**
 * Build a short summary from a skill description.
 * Takes the first sentence or truncates at ~80 chars.
 */
function summarizeDescription(description: string): string {
  // Take text before the first period that ends a sentence
  const firstSentence = description.replace(/\. .+$/, '');
  // Remove the "Use when you want to" / "Use when you need to" prefix
  const cleaned = firstSentence
    .replace(/^Use when you (?:want|need) to\s+/i, '')
    .replace(/^Use (?:before|when)\s+/i, '');
  // Truncate if still long
  if (cleaned.length > 90) {
    return cleaned.slice(0, 87) + '...';
  }
  return cleaned;
}

/**
 * Build the skills CLAUDE.md section dynamically from the manifest.
 */
export function buildSkillsSection(version: string, skills: { name: string; description: string }[]): string {
  const lines: string[] = [];

  lines.push(`${SKILLS_BLOCK_START} v${version} -->`);
  lines.push('# Skills and Tools');
  lines.push('');
  lines.push(`> Auto-generated by \`frontmcp skills install\` (v${version}) — do not edit manually.`);
  lines.push('');
  lines.push('This project uses **FrontMCP skills** installed in `.claude/skills/`.');
  lines.push('Before writing code, search the installed skills for relevant guidance:');
  lines.push('');

  for (const skill of skills) {
    const summary = summarizeDescription(skill.description);
    lines.push(`- **${skill.name}** — ${summary}`);
  }

  lines.push('');
  lines.push(
    'When you need to implement something, **read the matching skill first** — it contains patterns, examples, and common mistakes to avoid.',
  );
  lines.push(SKILLS_BLOCK_END);
  lines.push('');

  return lines.join('\n');
}

export interface InstallOptions {
  provider?: 'claude' | 'codex';
  dir?: string;
  all?: boolean;
  tag?: string;
  category?: string;
}

/**
 * Ensure CLAUDE.md exists and contains an up-to-date skills section.
 *
 * - If markers exist: replaces the block between them (handles version updates).
 * - If legacy `# Skills and Tools` header exists (no markers): replaces it.
 * - If neither exists: prepends the block.
 * - If file doesn't exist: creates it with the block.
 */
export async function ensureClaudeMdSkillsInstructions(cwd: string): Promise<void> {
  const manifest = loadCatalog();
  const version = getSelfVersion();
  const section = buildSkillsSection(version, manifest.skills);
  const claudeMdPath = path.join(cwd, 'CLAUDE.md');

  if (await fileExists(claudeMdPath)) {
    let content = await readFile(claudeMdPath);

    if (content.includes(SKILLS_BLOCK_START)) {
      // Replace existing marker-bounded block
      const startIdx = content.indexOf(SKILLS_BLOCK_START);
      const endIdx = content.indexOf(SKILLS_BLOCK_END);
      if (endIdx !== -1) {
        const before = content.slice(0, startIdx);
        const after = content.slice(endIdx + SKILLS_BLOCK_END.length);
        // Trim leading newlines from after to avoid accumulating blank lines
        content = before + section + after.replace(/^\n+/, '\n');
      } else {
        // Malformed: start marker without end — replace from start marker to end of file section
        content = content.slice(0, startIdx) + section + '\n';
      }
    } else if (content.includes(LEGACY_SKILLS_MARKER)) {
      // Migrate legacy format: replace from the legacy header to the next markdown heading
      const legacyIdx = content.indexOf(LEGACY_SKILLS_MARKER);
      const before = content.slice(0, legacyIdx);
      const afterLegacy = content.slice(legacyIdx + LEGACY_SKILLS_MARKER.length);
      // Find the next markdown heading (# at start of line) after the legacy header
      const nextHeadingMatch = afterLegacy.match(/\n(?=# )/);
      const after = nextHeadingMatch ? afterLegacy.slice(nextHeadingMatch.index!) : '';
      content = before + section + after;
    } else {
      // No existing skills section — prepend
      content = section + '\n' + content;
    }

    await writeFile(claudeMdPath, content);
    console.log(`${c('green', '✓')} Updated ${c('cyan', 'CLAUDE.md')} with skills usage instructions`);
  } else {
    await writeFile(claudeMdPath, section);
    console.log(`${c('green', '✓')} Created ${c('cyan', 'CLAUDE.md')} with skills usage instructions`);
  }
}

export async function installSkill(name: string | undefined, options: InstallOptions): Promise<void> {
  const manifest = loadCatalog();
  const provider = options.provider ?? 'claude';
  const targetBase = options.dir ?? path.resolve(process.cwd(), PROVIDER_DIRS[provider] ?? PROVIDER_DIRS['claude']);
  const catalogDir = getCatalogDir();

  // Validate that exactly one selector is supplied
  const selectorCount = [options.all, options.tag, options.category, name].filter(Boolean).length;
  if (selectorCount > 1) {
    console.error(c('red', 'Options --all, --tag, --category, and <name> are mutually exclusive.'));
    console.log(c('gray', 'Provide exactly one selector to choose which skills to install.'));
    process.exit(1);
  }

  // Determine which skills to install
  let skills = manifest.skills;

  if (options.all) {
    // Install all skills
  } else if (options.tag) {
    const tag = options.tag;
    skills = skills.filter((s) => s.tags.includes(tag));
    if (skills.length === 0) {
      console.error(c('red', `No skills found with tag "${tag}".`));
      console.log(c('gray', "Use 'frontmcp skills list --tag <tag>' to see available tags."));
      process.exit(1);
    }
  } else if (options.category) {
    skills = skills.filter((s) => s.category === options.category);
    if (skills.length === 0) {
      console.error(c('red', `No skills found in category "${options.category}".`));
      console.log(c('gray', "Use 'frontmcp skills list' to see available categories."));
      process.exit(1);
    }
  } else if (name) {
    // Single skill install
    const entry = skills.find((s) => s.name === name);
    if (!entry) {
      console.error(c('red', `Skill "${name}" not found in catalog.`));
      console.log(c('gray', "Use 'frontmcp skills list' to see available skills."));
      process.exit(1);
    }
    skills = [entry];
  } else {
    console.error(c('red', 'Please specify a skill name, or use --all, --tag, or --category.'));
    process.exit(1);
  }

  // Install each skill
  let installed = 0;
  for (const entry of skills) {
    const targetDir = path.join(targetBase, entry.name);
    const sourceDir = path.join(catalogDir, entry.path);

    if (!(await fileExists(path.join(sourceDir, 'SKILL.md')))) {
      console.error(c('yellow', `  Skipped ${entry.name}: source SKILL.md not found`));
      continue;
    }

    await ensureDir(targetDir);
    await cp(sourceDir, targetDir, { recursive: true });
    installed++;

    console.log(
      `${c('green', '✓')} Installed ${c('bold', entry.name)} to ${c('cyan', path.relative(process.cwd(), targetDir))}`,
    );
  }

  if (installed === 0) {
    console.error(c('red', `No skills were installed (0/${skills.length} had valid SKILL.md files).`));
    process.exit(1);
  }

  if (skills.length > 1) {
    console.log(`\n${c('green', '✓')} Installed ${installed}/${skills.length} skills (provider: ${provider})`);
  }

  // For Claude provider: ensure CLAUDE.md has skills usage instructions
  if (provider === 'claude') {
    await ensureClaudeMdSkillsInstructions(process.cwd());
  }
}
