name: "Save Nx Cache"
description: "Saves Nx build cache to GitHub Actions cache"

inputs:
  cache-prefix:
    description: "Cache prefix (default: nx-cache)"
    required: false
    default: "nx-cache"

runs:
  using: "composite"
  steps:
    - name: Compute cache key
      id: cache-key
      shell: bash
      run: |
        if [ -n "${{ github.event.pull_request.number }}" ]; then
          REF_KEY="pr-${{ github.event.pull_request.number }}"
        else
          REF_KEY="${{ github.ref_name }}"
        fi
        LOCK_HASH="${{ hashFiles('yarn.lock') }}"
        echo "key=${{ inputs.cache-prefix }}-${REF_KEY}-${LOCK_HASH}" >> $GITHUB_OUTPUT

    - name: Save Nx cache
      uses: actions/cache/save@v4
      with:
        path: |
          .nx/cache
          .nx/workspace-data
        key: ${{ steps.cache-key.outputs.key }}
