// Re-export all auth interfaces from @frontmcp/auth
export type {
  PublicAccessConfig,
  LocalSigningConfig,
  ProviderConfig,
  RemoteProviderConfig,
  TokenStorageConfig,
  // Secure store config (#470)
  SecureStoreConfig,
  SecureStoreEncryptionConfig,
  SecureStoreCustomBackend,
  TokenRefreshConfig,
  SkippedAppBehavior,
  ConsentConfig,
  FederatedAuthConfig,
  IncrementalAuthConfig,
  UpstreamProviderOptions,
  LocalDcrConfig,
  LocalDcrClient,
  PublicAuthOptionsInterface,
  TransparentAuthOptionsInterface,
  LocalAuthOptionsInterface,
  RemoteAuthOptionsInterface,
  LocalOrRemoteAuthOptionsInterface,
  AuthOptionsInterface,
  AuthMode,
  // Local login customization + authenticate() (Checkpoint 3a)
  LoginFieldConfig,
  LoginSubjectConfig,
  LoginConfig,
  LoginRenderContext,
  AuthenticateInput,
  AuthenticateContext,
  AuthenticateCredential,
  AuthenticateSuccess,
  AuthenticateFailure,
  AuthenticateResult,
  AuthenticateFn,
  // Deprecated compat aliases
  OrchestratedLocalOptionsInterface,
  OrchestratedRemoteOptionsInterface,
  OrchestratedAuthOptionsInterface,
  OrchestratedType,
} from '@frontmcp/auth';
