// Re-export all shared schemas from @frontmcp/auth
export {
  publicAccessConfigSchema,
  localSigningConfigSchema,
  providerConfigSchema,
  remoteProviderConfigSchema,
  flatRemoteProviderFields,
  tokenStorageConfigSchema,
  tokenRefreshConfigSchema,
  skippedAppBehaviorSchema,
  consentConfigSchema,
  federatedAuthConfigSchema,
  incrementalAuthConfigSchema,
  cimdCacheConfigSchema,
  cimdSecurityConfigSchema,
  cimdNetworkConfigSchema,
  cimdConfigSchema,
} from '@frontmcp/auth';
export type {
  PublicAccessConfig,
  PublicAccessConfigInput,
  LocalSigningConfig,
  LocalSigningConfigInput,
  ProviderConfig,
  ProviderConfigInput,
  RemoteProviderConfig,
  RemoteProviderConfigInput,
  TokenStorageConfig,
  TokenStorageConfigInput,
  TokenRefreshConfig,
  TokenRefreshConfigInput,
  SkippedAppBehavior,
  ConsentConfig,
  ConsentConfigInput,
  FederatedAuthConfig,
  FederatedAuthConfigInput,
  IncrementalAuthConfig,
  IncrementalAuthConfigInput,
  CimdCacheConfig,
  CimdSecurityConfig,
  CimdNetworkConfig,
  CimdConfig,
  CimdConfigInput,
  RedisConfig,
} from '@frontmcp/auth';
