// Re-export all shared schemas from @frontmcp/auth
export {
  publicAccessConfigSchema,
  localSigningConfigSchema,
  providerConfigSchema,
  remoteProviderConfigSchema,
  flatRemoteProviderFields,
  tokenStorageConfigSchema,
  tokenStorageSqliteSchema,
  tokenRefreshConfigSchema,
  skippedAppBehaviorSchema,
  consentConfigSchema,
  federatedAuthConfigSchema,
  incrementalAuthConfigSchema,
  upstreamProviderSchema,
  localDcrClientSchema,
  localDcrConfigSchema,
  cimdCacheConfigSchema,
  cimdSecurityConfigSchema,
  cimdNetworkConfigSchema,
  cimdConfigSchema,
} from '@frontmcp/auth';
// NOTE: This module is a legacy re-export stub; the active SDK auth surface is
// ./index.ts (which re-exports directly from @frontmcp/auth).
export type {
  PublicAccessConfig,
  PublicAccessConfigInput,
  LocalSigningConfig,
  LocalSigningConfigInput,
  ProviderConfig,
  ProviderConfigInput,
  RemoteProviderConfig,
  RemoteProviderConfigInput,
  TokenStorageConfig,
  TokenStorageConfigInput,
  TokenStorageSqliteConfig,
  TokenRefreshConfig,
  TokenRefreshConfigInput,
  SkippedAppBehavior,
  ConsentConfig,
  ConsentConfigInput,
  FederatedAuthConfig,
  FederatedAuthConfigInput,
  IncrementalAuthConfig,
  IncrementalAuthConfigInput,
  UpstreamProviderOptionsZod,
  UpstreamProviderOptionsInput,
  LocalDcrClientConfigZod,
  LocalDcrClientConfigInput,
  LocalDcrConfigZod,
  LocalDcrConfigInput,
  CimdCacheConfig,
  CimdSecurityConfig,
  CimdNetworkConfig,
  CimdConfig,
  CimdConfigInput,
  RedisConfig,
} from '@frontmcp/auth';
