// common/types/options/auth/transport.deprecated.ts
// DEPRECATED: These schemas are kept for backward compatibility during migration.
// Use top-level transport config instead.
// DELETE after v1.0.0

import { z } from 'zod';
import { redisConfigSchema } from '../../../../auth/session/transport-session.types';

/**
 * @deprecated Use top-level transport config instead. This will be removed in v1.0.0.
 */
export const transportRecreationConfigSchema = z
  .object({
    enabled: z.boolean().default(false),
    redis: redisConfigSchema.optional(),
    defaultTtlMs: z.number().int().positive().default(3600000),
  })
  .refine(
    (data) => {
      if (data.enabled && !data.redis) {
        return false;
      }
      return true;
    },
    {
      message: 'Redis configuration is required when transport recreation is enabled',
      path: ['redis'],
    },
  );

/**
 * @deprecated Use top-level transport config instead. This will be removed in v1.0.0.
 */
export const transportConfigSchema = z.object({
  enableLegacySSE: z.boolean().default(false),
  enableSseListener: z.boolean().default(true),
  enableStreamableHttp: z.boolean().default(true),
  enableStatelessHttp: z.boolean().default(false),
  enableStatefulHttp: z.boolean().default(false),
  requireSessionForStreamable: z.boolean().default(true),
  recreation: z.lazy(() => transportRecreationConfigSchema).optional(),
});

/**
 * @deprecated Use TransportOptions from transport.options.ts instead
 */
export type TransportConfig = z.infer<typeof transportConfigSchema>;

/**
 * @deprecated Use TransportOptionsInput from transport.options.ts instead
 */
export type TransportConfigInput = z.input<typeof transportConfigSchema>;

/**
 * @deprecated Use TransportPersistenceConfig from transport.options.ts instead
 */
export type TransportRecreationConfig = z.infer<typeof transportRecreationConfigSchema>;

/**
 * @deprecated Use TransportPersistenceConfigInput from transport.options.ts instead
 */
export type TransportRecreationConfigInput = z.input<typeof transportRecreationConfigSchema>;

/**
 * Default transport configuration values.
 * Single source of truth - generated by parsing empty object through Zod schema.
 * @deprecated Use top-level transport config instead. This will be removed in v1.0.0.
 */
export const DEFAULT_TRANSPORT_CONFIG: TransportConfig = transportConfigSchema.parse({});
