/**
 * Dependency Resolution Module
 *
 * Provides CDN dependency resolution, import parsing, and file-based
 * component bundling support for FrontMCP UI widgets.
 *
 * @packageDocumentation
 */
export {
  type CDNProvider,
  type CDNPlatformType,
  type CDNProviderConfig,
  type CDNDependency,
  type BundleTarget,
  type FileBundleOptions,
  type FileTemplateConfig,
  type ImportMap,
  type ResolvedDependency,
  type ComponentBuildManifest,
  type BuildCacheStorage,
  type CacheStats,
  type CDNRegistryEntry,
  type CDNRegistry,
  type DependencyResolverOptions,
  type ParsedImport,
  type ParsedImportResult,
  type TemplateMode,
  type TemplateFormat,
  type TemplateSource,
  type UrlFetchResult,
  type ResolvedTemplate,
  type TemplateProcessingOptions,
  type ProcessedTemplate,
  detectTemplateMode,
  detectFormatFromPath,
} from './types';
export {
  cdnProviderSchema,
  cdnPlatformTypeSchema,
  cdnDependencySchema,
  type CDNDependencyInput,
  type CDNDependencyOutput,
  bundleTargetSchema,
  fileBundleOptionsSchema,
  type FileBundleOptionsInput,
  type FileBundleOptionsOutput,
  fileTemplateConfigSchema,
  type FileTemplateConfigInput,
  type FileTemplateConfigOutput,
  importMapSchema,
  type ImportMapInput,
  type ImportMapOutput,
  resolvedDependencySchema,
  type ResolvedDependencyInput,
  type ResolvedDependencyOutput,
  componentBuildManifestSchema,
  buildManifestMetadataSchema,
  buildManifestOutputsSchema,
  type ComponentBuildManifestInput,
  type ComponentBuildManifestOutput,
  cdnProviderConfigSchema,
  cdnRegistryEntrySchema,
  packageMetadataSchema,
  type CDNRegistryEntryInput,
  type CDNRegistryEntryOutput,
  dependencyResolverOptionsSchema,
  type DependencyResolverOptionsInput,
  type DependencyResolverOptionsOutput,
  importTypeSchema,
  parsedImportSchema,
  parsedImportResultSchema,
  type ParsedImportInput,
  type ParsedImportOutput,
  type ParsedImportResultInput,
  type ParsedImportResultOutput,
  cacheStatsSchema,
  type CacheStatsInput,
  type CacheStatsOutput,
  type SafeParseResult,
  validateCDNDependency,
  safeParseCDNDependency,
  validateFileTemplateConfig,
  safeParseFileTemplateConfig,
  validateBuildManifest,
  safeParseBuildManifest,
} from './schemas';
export {
  DEFAULT_CDN_REGISTRY,
  CDN_PROVIDER_PRIORITY,
  lookupPackage,
  getPackageCDNUrl,
  getPackageCDNDependency,
  getRegisteredPackages,
  isPackageRegistered,
  mergeRegistries,
  getPackagePeerDependencies,
  resolveAllDependencies,
} from './cdn-registry';
export {
  parseImports,
  extractExternalPackages,
  filterImportsByPackages,
  getImportStats,
  getPackageName,
} from './import-parser';
export {
  DependencyResolver,
  createResolver,
  createClaudeResolver,
  createOpenAIResolver,
  resolveDependencies,
  generateImportMapForPackages,
  DependencyResolutionError,
  NoProviderError,
} from './resolver';
export {
  createImportMap,
  createImportMapFromOverrides,
  mergeImportMaps,
  addScope,
  generateImportMapScriptTag,
  generateImportMapScriptTagMinified,
  generateUMDShim,
  generateCDNScriptTags,
  generateESMScriptTags,
  generateDependencyHTML,
  validateImportMap,
  type UMDShimOptions,
  type DependencyHTMLOptions,
} from './import-map';
export {
  detectTemplateSource,
  isFileBasedTemplate,
  validateTemplateUrl,
  detectFormatFromUrl,
  fetchTemplateFromUrl,
  type FetchTemplateOptions,
  readTemplateFromFile,
  resolveFilePath,
  type ReadTemplateOptions,
  resolveTemplate,
  type ResolveTemplateOptions,
  getUrlCache,
  clearUrlCache,
  needsRefetch,
  invalidateUrlCache,
} from './template-loader';
export {
  processTemplate,
  processTemplates,
  supportsHandlebars,
  producesHtml,
  requiresBundling,
  processHtmlTemplate,
  processMarkdownTemplate,
  processMdxTemplate,
  clearHandlebarsCache,
  isMarkedAvailable,
} from './template-processor';
//# sourceMappingURL=index.d.ts.map
